### PR TITLE
Count-digits-trick

### PR DESCRIPTION
**Pull request by kalvik09**
One line trick to count digits in a number.

### CODE REVIEW

**Comment by AlgoMessiahs** [comment]
its Empty

**Comment by kalvik09** [comment]
its a docx file, please check again

**Comment by kalvik09** [comment]
do i make a pull request again?

**Comment by AlgoMessiahs** [comment]
Submit a valid Java Code not just a Equation

**Comment by kalvik09** [comment]
okay I got it, Please remove the spam label.
Thank you

**Comment by AlgoMessiahs** [comment]
Make another pull Request!

**Comment by kalvik09** [comment]
python code accepted??

**Comment by AlgoMessiahs** [comment]
yes

**Pull request closed without merging**
